let randomIDH = () => Math.round(Math.random() * (100 - 1) + 1) / 100;

// DATA
const data2010 = [
  { id: "AGS", año: 2010, estado: "Aguascalientes", idh: randomIDH() },
  { id: "BC", año: 2010, estado: "Baja California", idh: randomIDH() },
  { id: "BCS", año: 2010, estado: "Baja California Sur", idh: randomIDH() },
  { id: "CAMP", año: 2010, estado: "Campeche", idh: randomIDH() },
  { id: "CHIS", año: 2010, estado: "Chiapas", idh: randomIDH() },
  { id: "CHIH", año: 2010, estado: "Chihuahua", idh: randomIDH() },
  { id: "CDMX", año: 2010, estado: "CDMX", idh: randomIDH() },
  { id: "COAH", año: 2010, estado: "Coahuila", idh: randomIDH() },
  { id: "COL", año: 2010, estado: "Colima", idh: randomIDH() },
  { id: "DGO", año: 2010, estado: "Durango", idh: randomIDH() },
  { id: "GTO", año: 2010, estado: "Guanajuato", idh: randomIDH() },
  { id: "GRO", año: 2010, estado: "Guerrero", idh: randomIDH() },
  { id: "HGO", año: 2010, estado: "Hidalgo", idh: randomIDH() },
  { id: "JAL", año: 2010, estado: "Jalisco", idh: randomIDH() },
  { id: "EDOMEX", año: 2010, estado: "Edo México", idh: randomIDH() },
  { id: "MICH", año: 2010, estado: "Michoacan", idh: randomIDH() },
  { id: "MOR", año: 2010, estado: "Morelia", idh: randomIDH() },
  { id: "NAY", año: 2010, estado: "Nayarit", idh: randomIDH() },
  { id: "NL", año: 2010, estado: "Nuevo Leon", idh: randomIDH() },
  { id: "OAX", año: 2010, estado: "Oaxaca", idh: randomIDH() },
  { id: "PUE", año: 2010, estado: "Puebla", idh: randomIDH() },
  { id: "QRO", año: 2010, estado: "Queretaro", idh: randomIDH() },
  { id: "QROO", año: 2010, estado: "Quinta Roo", idh: randomIDH() },
  { id: "SLP", año: 2010, estado: "San Luis Potosi", idh: randomIDH() },
  { id: "SIN", año: 2010, estado: "Sinaloa", idh: randomIDH() },
  { id: "SON", año: 2010, estado: "Sonora", idh: randomIDH() },
  { id: "TAB", año: 2010, estado: "Tabasco", idh: randomIDH() },
  { id: "TAMPS", año: 2010, estado: "Tamaulipas", idh: randomIDH() },
  { id: "TLAX", año: 2010, estado: "Tlaxcala", idh: randomIDH() },
  { id: "VER", año: 2010, estado: "Veracruz", idh: randomIDH() },
  { id: "YUC", año: 2010, estado: "Yucatan", idh: randomIDH() },
  { id: "ZAC", año: 2010, estado: "Zacatecas", idh: randomIDH() },
];
const data2011 = [
  { id: "AGS", año: 2011, estado: "Aguascalientes", idh: randomIDH() },
  { id: "BC", año: 2011, estado: "Baja California", idh: randomIDH() },
  { id: "BCS", año: 2011, estado: "Baja California Sur", idh: randomIDH() },
  { id: "CAMP", año: 2011, estado: "Campeche", idh: randomIDH() },
  { id: "CHIS", año: 2011, estado: "Chiapas", idh: randomIDH() },
  { id: "CHIH", año: 2011, estado: "Chihuahua", idh: randomIDH() },
  { id: "CDMX", año: 2011, estado: "CDMX", idh: randomIDH() },
  { id: "COAH", año: 2011, estado: "Coahuila", idh: randomIDH() },
  { id: "COL", año: 2011, estado: "Colima", idh: randomIDH() },
  { id: "DGO", año: 2011, estado: "Durango", idh: randomIDH() },
  { id: "GTO", año: 2011, estado: "Guanajuato", idh: randomIDH() },
  { id: "GRO", año: 2011, estado: "Guerrero", idh: randomIDH() },
  { id: "HGO", año: 2011, estado: "Hidalgo", idh: randomIDH() },
  { id: "JAL", año: 2011, estado: "Jalisco", idh: randomIDH() },
  { id: "EDOMEX", año: 2011, estado: "Edo México", idh: randomIDH() },
  { id: "MICH", año: 2011, estado: "Michoacan", idh: randomIDH() },
  { id: "MOR", año: 2011, estado: "Morelia", idh: randomIDH() },
  { id: "NAY", año: 2011, estado: "Nayarit", idh: randomIDH() },
  { id: "NL", año: 2011, estado: "Nuevo Leon", idh: randomIDH() },
  { id: "OAX", año: 2011, estado: "Oaxaca", idh: randomIDH() },
  { id: "PUE", año: 2011, estado: "Puebla", idh: randomIDH() },
  { id: "QRO", año: 2011, estado: "Queretaro", idh: randomIDH() },
  { id: "QROO", año: 2011, estado: "Quinta Roo", idh: randomIDH() },
  { id: "SLP", año: 2011, estado: "San Luis Potosi", idh: randomIDH() },
  { id: "SIN", año: 2011, estado: "Sinaloa", idh: randomIDH() },
  { id: "SON", año: 2011, estado: "Sonora", idh: randomIDH() },
  { id: "TAB", año: 2011, estado: "Tabasco", idh: randomIDH() },
  { id: "TAMPS", año: 2011, estado: "Tamaulipas", idh: randomIDH() },
  { id: "TLAX", año: 2011, estado: "Tlaxcala", idh: randomIDH() },
  { id: "VER", año: 2011, estado: "Veracruz", idh: randomIDH() },
  { id: "YUC", año: 2011, estado: "Yucatan", idh: randomIDH() },
  { id: "ZAC", año: 2011, estado: "Zacatecas", idh: randomIDH() },
];
const data2012 = [
  { id: "AGS", año: 2012, estado: "Aguascalientes", idh: randomIDH() },
  { id: "BC", año: 2012, estado: "Baja California", idh: randomIDH() },
  { id: "BCS", año: 2012, estado: "Baja California Sur", idh: randomIDH() },
  { id: "CAMP", año: 2012, estado: "Campeche", idh: randomIDH() },
  { id: "CHIS", año: 2012, estado: "Chiapas", idh: randomIDH() },
  { id: "CHIH", año: 2012, estado: "Chihuahua", idh: randomIDH() },
  { id: "CDMX", año: 2012, estado: "CDMX", idh: randomIDH() },
  { id: "COAH", año: 2012, estado: "Coahuila", idh: randomIDH() },
  { id: "COL", año: 2012, estado: "Colima", idh: randomIDH() },
  { id: "DGO", año: 2012, estado: "Durango", idh: randomIDH() },
  { id: "GTO", año: 2012, estado: "Guanajuato", idh: randomIDH() },
  { id: "GRO", año: 2012, estado: "Guerrero", idh: randomIDH() },
  { id: "HGO", año: 2012, estado: "Hidalgo", idh: randomIDH() },
  { id: "JAL", año: 2012, estado: "Jalisco", idh: randomIDH() },
  { id: "EDOMEX", año: 2012, estado: "Edo México", idh: randomIDH() },
  { id: "MICH", año: 2012, estado: "Michoacan", idh: randomIDH() },
  { id: "MOR", año: 2012, estado: "Morelia", idh: randomIDH() },
  { id: "NAY", año: 2012, estado: "Nayarit", idh: randomIDH() },
  { id: "NL", año: 2012, estado: "Nuevo Leon", idh: randomIDH() },
  { id: "OAX", año: 2012, estado: "Oaxaca", idh: randomIDH() },
  { id: "PUE", año: 2012, estado: "Puebla", idh: randomIDH() },
  { id: "QRO", año: 2012, estado: "Queretaro", idh: randomIDH() },
  { id: "QROO", año: 2012, estado: "Quinta Roo", idh: randomIDH() },
  { id: "SLP", año: 2012, estado: "San Luis Potosi", idh: randomIDH() },
  { id: "SIN", año: 2012, estado: "Sinaloa", idh: randomIDH() },
  { id: "SON", año: 2012, estado: "Sonora", idh: randomIDH() },
  { id: "TAB", año: 2012, estado: "Tabasco", idh: randomIDH() },
  { id: "TAMPS", año: 2012, estado: "Tamaulipas", idh: randomIDH() },
  { id: "TLAX", año: 2012, estado: "Tlaxcala", idh: randomIDH() },
  { id: "VER", año: 2012, estado: "Veracruz", idh: randomIDH() },
  { id: "YUC", año: 2012, estado: "Yucatan", idh: randomIDH() },
  { id: "ZAC", año: 2012, estado: "Zacatecas", idh: randomIDH() },
];
const data2013 = [
  { id: "AGS", año: 2013, estado: "Aguascalientes", idh: randomIDH() },
  { id: "BC", año: 2013, estado: "Baja California", idh: randomIDH() },
  { id: "BCS", año: 2013, estado: "Baja California Sur", idh: randomIDH() },
  { id: "CAMP", año: 2013, estado: "Campeche", idh: randomIDH() },
  { id: "CHIS", año: 2013, estado: "Chiapas", idh: randomIDH() },
  { id: "CHIH", año: 2013, estado: "Chihuahua", idh: randomIDH() },
  { id: "CDMX", año: 2013, estado: "CDMX", idh: randomIDH() },
  { id: "COAH", año: 2013, estado: "Coahuila", idh: randomIDH() },
  { id: "COL", año: 2013, estado: "Colima", idh: randomIDH() },
  { id: "DGO", año: 2013, estado: "Durango", idh: randomIDH() },
  { id: "GTO", año: 2013, estado: "Guanajuato", idh: randomIDH() },
  { id: "GRO", año: 2013, estado: "Guerrero", idh: randomIDH() },
  { id: "HGO", año: 2013, estado: "Hidalgo", idh: randomIDH() },
  { id: "JAL", año: 2013, estado: "Jalisco", idh: randomIDH() },
  { id: "EDOMEX", año: 2013, estado: "Edo México", idh: randomIDH() },
  { id: "MICH", año: 2013, estado: "Michoacan", idh: randomIDH() },
  { id: "MOR", año: 2013, estado: "Morelia", idh: randomIDH() },
  { id: "NAY", año: 2013, estado: "Nayarit", idh: randomIDH() },
  { id: "NL", año: 2013, estado: "Nuevo Leon", idh: randomIDH() },
  { id: "OAX", año: 2013, estado: "Oaxaca", idh: randomIDH() },
  { id: "PUE", año: 2013, estado: "Puebla", idh: randomIDH() },
  { id: "QRO", año: 2013, estado: "Queretaro", idh: randomIDH() },
  { id: "QROO", año: 2013, estado: "Quinta Roo", idh: randomIDH() },
  { id: "SLP", año: 2013, estado: "San Luis Potosi", idh: randomIDH() },
  { id: "SIN", año: 2013, estado: "Sinaloa", idh: randomIDH() },
  { id: "SON", año: 2013, estado: "Sonora", idh: randomIDH() },
  { id: "TAB", año: 2013, estado: "Tabasco", idh: randomIDH() },
  { id: "TAMPS", año: 2013, estado: "Tamaulipas", idh: randomIDH() },
  { id: "TLAX", año: 2013, estado: "Tlaxcala", idh: randomIDH() },
  { id: "VER", año: 2013, estado: "Veracruz", idh: randomIDH() },
  { id: "YUC", año: 2013, estado: "Yucatan", idh: randomIDH() },
  { id: "ZAC", año: 2013, estado: "Zacatecas", idh: randomIDH() },
];
const data2014 = [
  { id: "AGS", año: 2014, estado: "Aguascalientes", idh: randomIDH() },
  { id: "BC", año: 2014, estado: "Baja California", idh: randomIDH() },
  { id: "BCS", año: 2014, estado: "Baja California Sur", idh: randomIDH() },
  { id: "CAMP", año: 2014, estado: "Campeche", idh: randomIDH() },
  { id: "CHIS", año: 2014, estado: "Chiapas", idh: randomIDH() },
  { id: "CHIH", año: 2014, estado: "Chihuahua", idh: randomIDH() },
  { id: "CDMX", año: 2014, estado: "CDMX", idh: randomIDH() },
  { id: "COAH", año: 2014, estado: "Coahuila", idh: randomIDH() },
  { id: "COL", año: 2014, estado: "Colima", idh: randomIDH() },
  { id: "DGO", año: 2014, estado: "Durango", idh: randomIDH() },
  { id: "GTO", año: 2014, estado: "Guanajuato", idh: randomIDH() },
  { id: "GRO", año: 2014, estado: "Guerrero", idh: randomIDH() },
  { id: "HGO", año: 2014, estado: "Hidalgo", idh: randomIDH() },
  { id: "JAL", año: 2014, estado: "Jalisco", idh: randomIDH() },
  { id: "EDOMEX", año: 2014, estado: "Edo México", idh: randomIDH() },
  { id: "MICH", año: 2014, estado: "Michoacan", idh: randomIDH() },
  { id: "MOR", año: 2014, estado: "Morelia", idh: randomIDH() },
  { id: "NAY", año: 2014, estado: "Nayarit", idh: randomIDH() },
  { id: "NL", año: 2014, estado: "Nuevo Leon", idh: randomIDH() },
  { id: "OAX", año: 2014, estado: "Oaxaca", idh: randomIDH() },
  { id: "PUE", año: 2014, estado: "Puebla", idh: randomIDH() },
  { id: "QRO", año: 2014, estado: "Queretaro", idh: randomIDH() },
  { id: "QROO", año: 2014, estado: "Quinta Roo", idh: randomIDH() },
  { id: "SLP", año: 2014, estado: "San Luis Potosi", idh: randomIDH() },
  { id: "SIN", año: 2014, estado: "Sinaloa", idh: randomIDH() },
  { id: "SON", año: 2014, estado: "Sonora", idh: randomIDH() },
  { id: "TAB", año: 2014, estado: "Tabasco", idh: randomIDH() },
  { id: "TAMPS", año: 2014, estado: "Tamaulipas", idh: randomIDH() },
  { id: "TLAX", año: 2014, estado: "Tlaxcala", idh: randomIDH() },
  { id: "VER", año: 2014, estado: "Veracruz", idh: randomIDH() },
  { id: "YUC", año: 2014, estado: "Yucatan", idh: randomIDH() },
  { id: "ZAC", año: 2014, estado: "Zacatecas", idh: randomIDH() },
];
const data2015 = [
  { id: "AGS", año: 2015, estado: "Aguascalientes", idh: randomIDH() },
  { id: "BC", año: 2015, estado: "Baja California", idh: randomIDH() },
  { id: "BCS", año: 2015, estado: "Baja California Sur", idh: randomIDH() },
  { id: "CAMP", año: 2015, estado: "Campeche", idh: randomIDH() },
  { id: "CHIS", año: 2015, estado: "Chiapas", idh: randomIDH() },
  { id: "CHIH", año: 2015, estado: "Chihuahua", idh: randomIDH() },
  { id: "CDMX", año: 2015, estado: "CDMX", idh: randomIDH() },
  { id: "COAH", año: 2015, estado: "Coahuila", idh: randomIDH() },
  { id: "COL", año: 2015, estado: "Colima", idh: randomIDH() },
  { id: "DGO", año: 2015, estado: "Durango", idh: randomIDH() },
  { id: "GTO", año: 2015, estado: "Guanajuato", idh: randomIDH() },
  { id: "GRO", año: 2015, estado: "Guerrero", idh: randomIDH() },
  { id: "HGO", año: 2015, estado: "Hidalgo", idh: randomIDH() },
  { id: "JAL", año: 2015, estado: "Jalisco", idh: randomIDH() },
  { id: "EDOMEX", año: 2015, estado: "Edo México", idh: randomIDH() },
  { id: "MICH", año: 2015, estado: "Michoacan", idh: randomIDH() },
  { id: "MOR", año: 2015, estado: "Morelia", idh: randomIDH() },
  { id: "NAY", año: 2015, estado: "Nayarit", idh: randomIDH() },
  { id: "NL", año: 2015, estado: "Nuevo Leon", idh: randomIDH() },
  { id: "OAX", año: 2015, estado: "Oaxaca", idh: randomIDH() },
  { id: "PUE", año: 2015, estado: "Puebla", idh: randomIDH() },
  { id: "QRO", año: 2015, estado: "Queretaro", idh: randomIDH() },
  { id: "QROO", año: 2015, estado: "Quinta Roo", idh: randomIDH() },
  { id: "SLP", año: 2015, estado: "San Luis Potosi", idh: randomIDH() },
  { id: "SIN", año: 2015, estado: "Sinaloa", idh: randomIDH() },
  { id: "SON", año: 2015, estado: "Sonora", idh: randomIDH() },
  { id: "TAB", año: 2015, estado: "Tabasco", idh: randomIDH() },
  { id: "TAMPS", año: 2015, estado: "Tamaulipas", idh: randomIDH() },
  { id: "TLAX", año: 2015, estado: "Tlaxcala", idh: randomIDH() },
  { id: "VER", año: 2015, estado: "Veracruz", idh: randomIDH() },
  { id: "YUC", año: 2015, estado: "Yucatan", idh: randomIDH() },
  { id: "ZAC", año: 2015, estado: "Zacatecas", idh: randomIDH() },
];
